# Generated by Django 3.2.9 on 2021-12-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=40)),
                ('Company_Name', models.CharField(max_length=60)),
                ('Quantity_in_KG', models.IntegerField()),
                ('Contact_Number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
