# Generated by Django 3.2.9 on 2021-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Contact_Number',
            field=models.IntegerField(),
        ),
    ]
